# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0003_songs_song_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(default='', max_length=255)),
                ('subject', models.CharField(default='', max_length=255)),
                ('actor', models.CharField(default='', max_length=255)),
                ('actress', models.CharField(default='', max_length=255)),
                ('director', models.CharField(default='', max_length=255)),
                ('popularity', models.IntegerField(blank=True, null=True)),
                ('awards', models.BooleanField()),
                ('image', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
