# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 03:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0004_movie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='Movies',
        ),
    ]
